service_name: verse_spec
description: general testing of verse core.

logging:
  level: debug
  show_full_error: true
em:
  adapter: redis
  config:
    streams:
      "example:topic":
        maxlen: 5
plugins:
  - name: redis
    config:
      max_connections: 20